[package]
name = "cx-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cx-core.workspace = true
cx-ecs.workspace = true
cx-module.workspace = true
cx-fields.workspace = true
cx-time.workspace = true
cx-diag.workspace = true
cx-worldgen.workspace = true
cx-spatial.workspace = true
cx-agents.workspace = true

[lints]
workspace = true
