[package]
name = "chromatron-game"
description = "Windowed client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cx-app.workspace = true
cx-core.workspace = true
cx-ecs.workspace = true
cx-render.workspace = true
cx-view.workspace = true
cx-worldgen.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints.rust]
unsafe_code = "warn"
